<div class="rlink gaming"><div class="rinfo"><span class="rtitle"><a href="https://i.redd.it/48cng0vxz1ky.jpg">My gf is annoying on snap..</a></span><br /><span class="rtext">I don't think you understand the purpose of this e...</span></div><div class="tag"></div></div>
<div class="rlink gaming"><div class="rinfo"><span class="rtitle"><a href="https://i.redd.it/p42bv4xex1ky.jpg">My gf thinks she's sexy</a></span><br /><span class="rtext">What is the point of this post? ...</span></div><div class="tag"></div></div>
<div class="rlink gaming"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/gaming/comments/5y3jnr/is_it_worth_getting_elder_scrolls_oblivion_in_2017/">Is it worth getting Elder Scrolls Oblivion in 2017?</a></span><br /><span class="rtext">If you can't handle outdated graphics then no. If ...</span></div><div class="tag"></div></div>
<div class="rlink gaming"><div class="rinfo"><span class="rtitle"><a href="http://i.imgur.com/AzjJSGm.jpg">Parasite Eve-inspired art</a></span><br /><span class="rtext">The heartwarming story of how a cripple saves Chri...</span></div><div class="tag"></div></div>
<div class="rlink modernmagic"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/ModernMagic/comments/5y2q8k/feedback_and_advice_for_bant_knightfall/">Feedback and Advice for Bant Knightfall</a></span><br /><span class="rtext">I think geist is one of the best creatures in the ...</span></div><div class="tag"></div></div>
<div class="rlink modernmagic"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/ModernMagic/comments/5y2sz5/bant_eldrazi_or_eldrazi_and_taxes/">Bant eldrazi or eldrazi and taxes?</a></span><br /><span class="rtext">Bant Eldrazi is definitely the better performer of...</span></div><div class="tag"></div></div>
<div class="rlink modernmagic"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/ModernMagic/comments/5y2tiv/the_rock_vs_bgx/">The Rock vs. BGx?</a></span><br /><span class="rtext">I've tried it. It boils down to whether or not gho...</span></div><div class="tag"></div></div>
<div class="rlink modernmagic"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/ModernMagic/comments/5y2vmj/modern_states_inventor_of_cheeri0s_is_bad_at_his/">Modern States: Inventor of Cheeri0s is Bad At His Ow...</a></span><br /><span class="rtext">This has been my experience playing against Cheeri...</span></div><div class="tag"></div></div>
<div class="rlink modernmagic"><div class="rinfo"><span class="rtitle"><a href="https://www.reddit.com/r/ModernMagic/comments/5y33ou/ive_just_created_a_discord_all_about_norin_the/">I've just created a Discord all about Norin the Wary.</a></span><br /><span class="rtext">Funny because nobody is ever there. /s...</span></div><div class="tag"></div></div>
<div class="rlink gaming"><div class="rinfo"><span class="rtitle"><a href="https://i.redd.it/6epetinvx1ky.jpg">Vault 7?!? Oh.....</a></span><br /><span class="rtext">The main purpose of this vault was to observe how ...</span></div><div class="tag"></div></div>
